# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Kuldeep Sengar
title: Engineering Lead
email: sengar.kuldeep@gmail.com
website: sengarkuldeep.com
# Social links
twitter_username: kuldeep_sengar
github_username: kuldeepsengar
linkedin_username: sengarkuldeep
youtube_username: KuldeepSengarSingh

# About Section
about_title: Summary
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
    Engineering Leader with 15+ years of diverse experience working across high-growth startups like Gojek, as well as, top-tier investment Banks like Deutsche Bank and RBS. Have a rich experience in leading complex projects from early vision to a workable solution. Hands on in engineering, comfortable taking multiple responsibilities as backend architect or manage teams/projects.
    I'm proficient in building large scale applications that could work under high load. I'm also passionate about helping team grow by mentoring engineers and driving continual improvement initiatives on engineering practices - especially around coding, testing, devops and SRE.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
